### ISSUE TITLE
Mobile - Inicialização do ambiente de desenvolvimento

### ISSUE THREAD

**Issue by savio591** [codestation-boys/gymstation-mobile#1]
* Inicializar o ambiente de desenvolvimento com React Native
- [x] Criar uma nova branch chamada "dev"
- [x] Fazer o checkout para a "dev" branch
- [x] Instalar dependências do env React Native
- [x] Remover as telas de demonstração e adicionar um "Hello World!".
- [x] Testar o funcionamento do "Hello world"

**Comment by CesarJs** [comment]
Finish Task
